# Generated by Django 6.0 on 2026-02-07 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0002_alter_association_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_at', models.DateField()),
                ('finish_at', models.DateField()),
                ('status', models.CharField(choices=[('مُقْبِل', 'À venir'), ('اِنْتَهَى', 'Fini'), ('ألغت', 'Annulé')], default='À venir', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Events/')),
                ('association', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='association_event', to='UserApp.association')),
            ],
        ),
    ]
