# Generated by Django 6.0 on 2026-02-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='n_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'مُقْبِل'), ('finished', 'اِنْتَهَى'), ('cancelled', 'ألغت')], default='À venir', max_length=10),
        ),
    ]
