# Generated by Django 6.0 on 2026-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_eventfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Bientôt'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='Bientôt', max_length=10),
        ),
    ]
