# Generated by Django 6.0 on 2026-02-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='category',
            field=models.CharField(choices=[('إِنْسَانِي', 'Humanitaire'), ('مكافحة الفقر', 'Lutte contre la pauvreté'), ('صِحَّة', 'Santé'), ('تَعْلِيم', 'Éducation'), ('بِيئَة', 'Environnement'), ('قضية اجتماعية', 'Cause sociale')], max_length=100),
        ),
    ]
