# Generated by Django 6.0 on 2026-02-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_association_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='receipt',
            field=models.ImageField(default=None, upload_to='Receipt'),
        ),
        migrations.AlterField(
            model_name='association',
            name='category',
            field=models.CharField(choices=[('humanitary', 'إِنْسَانِي'), ('fight against poverty', 'مكافحة الفقر'), ('health', 'صِحَّة'), ('education', 'تَعْلِيم'), ('environment', 'بِيئَة'), ('social case', 'قضية اجتماعية')], max_length=100),
        ),
    ]
