# Generated by Django 6.0 on 2026-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_association_receipt_alter_association_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
