# Generated by Django 6.0 on 2026-02-07 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('handicap', 'إعاقة'), ('maladies', 'أمراض'), ('enfants', 'أطفال'), ('education', 'تعليم'), ('renovation', 'ترميم'), ('autres', 'أخرى')], default='autres', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Announcements/')),
                ('description', models.TextField()),
                ('beneficiary', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='AnnouncementApp.announcement')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
