# Generated by Django 6.0 on 2026-02-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
