# Generated by Django 6.0 on 2026-02-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0002_announcement_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
