# Generated by Django 6.0 on 2026-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0003_alter_announcement_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant plafond à atteindre', max_digits=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('handicap', 'إعاقة'), ('maladies', 'أمراض'), ('enfants', 'أطفال'), ('education', 'تعليم'), ('renovation', 'ترميم')], default='handicap', max_length=20),
        ),
    ]
