# Generated by Django 6.0 on 2026-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0004_announcement_target_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant plafond à atteindre', max_digits=10),
        ),
    ]
