# Generated by Django 6.0.2 on 2026-02-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0005_alter_announcement_target_amount'),
        ('UserApp', '0003_association_receipt_alter_association_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='association',
            field=models.ForeignKey(blank=True, help_text='Association ayant créé cette annonce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='UserApp.association'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant actuellement collecté', max_digits=10),
        ),
    ]
