# Generated by Django 6.0.2 on 2026-02-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0006_announcement_association_announcement_current_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='current_amount',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_amount_achieved',
            field=models.BooleanField(default=False, help_text='Indique si le montant cible a été atteint'),
        ),
    ]
