# Generated by Django 6.0 on 2026-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementApp', '0007_remove_announcement_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('handicap', 'Handicap'), ('maladies', 'Maladies'), ('enfants', 'Enfants'), ('education', 'Education'), ('renovation', 'Renovation')], default='handicap', max_length=20),
        ),
    ]
